# Uncomment the next line to define a global platform for your project
platform :ios, '18.2'

target 'iosApp' do
  use_frameworks!

  platform :ios, '18.2'
    pod 'shared', :path => '../shared'
    pod 'Firebase/Auth'
    pod 'Firebase/Firestore'
    pod 'Firebase/Storage'
    pod 'Firebase/Analytics'
    pod 'ToastSwiftUI'
    pod 'SwiftLint'
    pod 'Shuffle-iOS'
    pod 'Instructions', '~> 2.3.0'
    pod 'GoogleSignIn'

end
